### PR TITLE
Add option to log stderr even if a command finishes with exit code 0

### PR DESCRIPTION
**Pull request by mluscon**
Unfortunately, by default java cmdline utilities log their standard output to stderr and there is currently no way in prefect-shell how to log stderr if a command finishes successfully.

An open question to me remains whether the stderr should be logged by default in prefect-shell or not. Let me know  if you agree with my approach and I will supply some tests.

### CODE REVIEW

**Comment by ahuang11** [comment]
Thanks for submitting a PR to fix this! I was wondering, if you used this util from core Prefect, does it stream output since both are streamed to PIPE?
https://github.com/PrefectHQ/prefect/blob/95f3cbf24adbac4325e014f6531ddbeee975eb92/src/prefect/utilities/processutils.py#L54-L93

`from prefect.utilities.processutils import run_process`

**Comment by ahuang11** [comment]
Yes, but I think the original task might not be changed. Instead, it'll come on as a new interface as a Block method.

**Comment by ahuang11** [comment]
I created a draft of it here: https://github.com/PrefectHQ/prefect-shell/pull/55; I don't think it works as intended yet though.

**Comment by ddresslerlegalplans** [comment]
Also ran into a similar issue where the stderr message was never returned in the output and therefore was unable to learn about an error in the shell command being ran by the prefect flow.  

Should we instead be using subprocess (https://docs.python.org/3/library/subprocess.html) instead of prefect-shell? and using a try catch on subprocess.CalledProcessError to know when an error is occuring in a shell command?

pseudo code
```python
import subprocess

try:
    subprocess.check_output('ls', shell=True)
except subprocess.CalledProcessError as e:
    get_run_logger().info(e.returncode)
    get_run_logger().info(e.output)
```

**Comment by ahuang11** [comment]
Thanks for sharing! Do you have an example of a shell command that I can test with so when I continue #55, I can ensure the behavior is expected?

**Comment by ddresslerlegalplans** [comment]
This not my exact case, but could be used to make sure stderr is coming back.

```sh
echo This message goes to stderr >&2
```

**Comment by ahuang11** [comment]
I apologize for the late reply, but I finally had some time to tinker with prefect-shell and I think #55 now satisfies this requirement:
```
from prefect_shell.commands import ShellOperation
shell_operation = ShellOperation(commands=["echo This message goes to stderr >&2"])
shell_operation.run()
```

image

Hoping to release it sometime this week!

**Comment by ddresslerlegalplans** [comment]
nice job and thanks for fixing it

**Comment by ahuang11** [comment]
You're welcome! Hoping to release it soon!

**Comment by mluscon** [comment]
Thanks a lot! Great job.

**Pull request closed without merging**
